### ISSUE TITLE
Some runs are not counted if there exists a better PB

### ISSUE THREAD

**Issue by Geekid812** [Geekid812/TrackmaniaBingo#6]
For some reason. let's try and find out why

**Comment by Geekid812** [comment]
Update: looking for people who can reproduce this issue, or any issue regarding a time that is not submitted as a claim when it should! please let me know the circumstances under which this bug happens in this issue :eyes:

**Comment by XertroV** [comment]
WRT the circumstances under which it happens, I suspect it's because of how you access the ghost, here: https://github.com/Geekid812/TrackmaniaBingo/blob/3a5de0ccd1e8d4f4c1745c89cc83b70be7db847d/src/play.as#L70

The way TTG does it is to track the number of ghosts, and then when a finish is detected, wait for the number of ghosts to increase and then get the most recent ghosts time.

- getting ghost data: https://github.com/XertroV/tm-cgf-library/blob/200b8ba451b347fe5b503a00b3677cb79a65c8e7/src/GameHelpers.as#L40-L50
- usage: https://github.com/XertroV/tm-cgf-library/blob/200b8ba451b347fe5b503a00b3677cb79a65c8e7/src/TTG/TTGState.as#L749-L750

Additionally:

* when playing online, all ghosts are accessible via the method above: `app.Network.ClientManiaAppPlayground.DataFileMgr.Ghosts`
* when playing locally, new ghosts are accessible via the method above, **but** the PB ghost is loaded into `app.PlaygroundScript.DataFileMgr.Ghosts` (new ghosts also appear here, but are removed again later).

In both cases, record ghosts get loaded into `app.Network.ClientManiaAppPlayground.DataFileMgr.Ghosts`.
So you need to either check the nickname on the ghost, or just tolerate that there's a tiny race condition where someone could load a record ghost at the exact moment they finish or something like that.

My suspicion is that `PlaygroundScript.Ghost_RetrieveFromPlayer` is acting like a server would, which will return the best ghost for that player. You could test this by getting e.g., a 20s run, checking the time returned, then getting a 30s run, and checking the time returned (my prediction is that it'll be 20s not 30s). 

This sort of bug would only matter if ppl already had a PB on the map -- and if the PB ghost loaded, **which doesn't seem to always happen**. Once they get a time, the best ghost isn't their new ghost, it's their PB.
